services:
  certbot:
    build: ./certbot
    ports:
      - 80:80
    volumes:
      - ./config/certs:/certs
    restart: no
    env_file: ./.env
    environment:
      - DRY_RUN=${DRY_RUN}
      - EMAIL=${CERTBOT_EMAIL}
      - DOMAINS=${CERTBOT_DOMAINS}
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M

  ocserv:
    build: ./ocserv
    ports:
      - 443:443
    volumes:
      - ./config/certs:/certs
      - ./config/ocserv-passwd:/config/ocserv-passwd
    restart: always
    env_file: ./.env
    environment:
      - CAMOUFLAGE_SECRET=${CAMOUFLAGE_SECRET:-mysecretkey}
      - DOMAIN=${OCSERV_DOMAIN}
      - PASSWD=${OCSERV_PASSWD}
      - MAX_CLIENTS=10
      - IPV4_NETWORK=10.10.11.0/24
    depends_on:
      certbot:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
